// Writes config.js from SUPABASE_URL / SUPABASE_ANON_KEY.
// Locally: reads them from .env.   On Vercel: reads them from Project Settings > Environment Variables.
// Usage: node scripts/make-config.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const env = { ...readDotEnv(path.join(root, '.env')), ...pick(process.env) };

function pick(src) {
  const out = {};
  for (const k of ['SUPABASE_URL', 'SUPABASE_ANON_KEY']) if (src[k]) out[k] = src[k];
  return out;
}
function readDotEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith('#')) out[m[1]] = m[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return out;
}

const url = (env.SUPABASE_URL || '').trim();
const key = (env.SUPABASE_ANON_KEY || '').trim();
if (!url || !key) {
  console.warn('make-config: SUPABASE_URL / SUPABASE_ANON_KEY not set, so cloud sync will be off.');
}

const body = `// Generated by scripts/make-config.js from .env (or Vercel environment variables). The anon key is public by design.
window.CRAMVIEW_CONFIG = {
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)},
};
`;
fs.writeFileSync(path.join(root, 'config.js'), body);
console.log(`make-config: wrote config.js (${url && key ? 'sync enabled' : 'sync off'})`);
